spring.application.name=ecommerce-backend

# database connection (MySQL & PostgreSQL)

# MySQL


# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_analytics_platform_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update

# SQL sorgular?n? konsolda görmek için
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Veritaban? lehçesi (Dialect)
# spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# JWT Ayar?
jwt.secret=${jwt_secret}
# 4 saat
jwt.expiration=14400000
# 12 saat
jwt.refresh-token.expiration=43200000

# Swagger/OpenAPI Path
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Gemini API Key
google.gemini.api.key=${GEMINI_API_KEY}

# CORS Settings
app.cors.allowed-origins=http://localhost:4200