spring.application.name=ecommerce-backend

# Database
spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.ivordzmgpweapxljeuis
spring.datasource.password=vq8aaXjPgBsS8MR8

spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.idle-timeout=30000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=06e70c5bf843ce26b23d17f3f3af491e390dfc0ab5adcdab7733df5fb77d18648b977103027d9618
jwt.expiration=900000
jwt.refresh-token.expiration=259200000

# Swagger/OpenAPI Path
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Gemini (legacy)
google.gemini.api.key=AIzaSyBBKg4-HRb3u3lYrKek04MYvzLC4_bbAFA

# CORS
app.cors.allowed-origins=http://localhost:4200

# Mail
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=6e3ba288f3cee4
spring.mail.password=ac0e75e69586cc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.from=noreply@ecommerce.com
app.mail.base-url=http://localhost:4200

# Stripe Settings
stripe.secret.key=${STRIPE_SECRET_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET_KEY}

# Text-to-SQL Agent
ai.agent.url=http://127.0.0.1:8000/chat
