spring.application.name=ecommerce-backend

# database connection (MySQL & PostgreSQL)

# MySQL


# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_analytics_platform_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update

# SQL sorgular?n? konsolda görmek için
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Veritaban? lehçesi (Dialect)
# spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# JWT Ayar?
jwt.secret=${jwt_secret}
# 15 dakika
jwt.expiration=900000
# 3 gün
jwt.refresh-token.expiration=259200000

# Swagger/OpenAPI Path
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Gemini API Key
google.gemini.api.key=${GEMINI_API_KEY}

# CORS Settings
app.cors.allowed-origins=http://localhost:4200


# Mail Settings
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=${mailtrap_username}
spring.mail.password=${mailtrap_password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.from=noreply@ecommerce.com
app.mail.base-url=http://localhost:4200